version: '3'

services:
  backend:
    container_name: "go_backend"
    tty: true
    image: golang:1.15-alpine
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    command: go run cmd/main/main.go
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    ports:
      - 80:80
      - 443:443

  db:
    container_name: "mysql"
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306

  redis:
    container_name: "redis"
    image: redis:alpine

  monitoring:
    container_name: "prometheus"
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
